Repository great-lakes/project-egypt, pull requests merged in 2018-06, with the labels that each got.

#29 Scruffyfurn/test integration
  .vs/slnx.sqlite
  README.md
  package.json
  src/components/App/App.test.js
  src/components/App/Test.examples.js
  yarn.lock
Labels: infrastructure

#30 Added travis yml file
  .travis.yml
Labels: infrastructure

#45 Implement basic header react component
  package-lock.json
  public/index.html
  src/components/App/App.css
  src/components/App/App.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.test.js
  src/components/NavBar/index.js
Labels: ui

#53 Gcrev93/GeneratorUpload
  reference/generatorUploadIntegration.html
  yarn.lock
Labels: generators

#68 addin explicit stage for pull request
  .travis.yml
  package.json
  src/components/HubCreation/HubCreationContainer.js
  yarn.lock
Labels: infrastructure

#74 Scruffyfurn/genviewfunc
  src/components/AvailableGenerators/AvailableGenerators.css
  src/components/AvailableGenerators/AvailableGenerators.js
  src/components/AvailableGenerators/AvailableGeneratorsContainer.js
  src/components/AvailableGenerators/index.js
  src/components/CustomGenerator/CustomGenerator.css
  src/components/CustomGenerator/CustomGenerator.js
  src/components/CustomGenerator/CustomGeneratorContainer.js
  src/components/CustomGenerator/index.js
  src/components/GeneratorInfo/GeneratorInfo.css
  src/components/GeneratorInfo/GeneratorInfo.js
  src/components/GeneratorInfo/GeneratorInfoContainer.js
  src/components/GeneratorInfo/index.js
  src/components/Generators/Generators.css
  src/components/Generators/Generators.js
  src/components/Generators/Generators.test.js
  src/modules/generators/actions.js
  src/modules/generators/reducer.js
  src/store/reducer.js
Labels: ui

#67 Kslhacks/generator localstorage
  reference/generatorUploadIntegration.html
Labels: generators

#84 Scruffyfurn/addhubview
  src/components/AddHub/AddHub.css
  src/components/AddHub/AddHub.js
  src/components/AddHub/AddHub.test.js
  src/components/HubCreation/HubCreation.css
  src/components/HubCreation/HubCreation.js
  src/components/TextInput/TextInput.js
Labels: ui
